-- ============================================================
-- Şahanlar Mühendislik — Tüm Başlangıç Verileri (MSSQL, seed_mssql.sql)
-- Sırayla çalıştırın: 1) schema_mssql.sql   2) seed_mssql.sql
-- ============================================================

-- ============================================================
-- Şahanlar Mühendislik — Başlangıç Verisi (MSSQL) — site_references
-- schema_mssql.sql'den SONRA çalıştırın.
-- ============================================================

-- Elektrik: 237 kayıt
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Ahmet Emrem',N'Tarımsal Sulama',N'Çivril',2025,100,N'kVa',50,0);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Aou Gıda',N'Tavuk Çiftliği',N'Çivril',2025,400,N'kVa',400,1);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Demirtaş Kömür',N'Ges Bağlantı Hattı',N'Çivril',2025,1000,N'kVa',500,2);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Harun Sarıkaya',N'Tavuk Çiftliği',N'Çivril',2025,400,N'kVa',900,3);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Ümit Çelik',N'Güç Yükseltimi',N'Çivril',2025,400,N'kVa',20,4);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Altıntop Kuruyemiş',N'Ges Bağlantı Hattı',N'Tavas',2024,1000,N'kVa',70,5);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Antav Hayvancılık',N'Tavuk Çiftliği',N'Çivril',2024,400,N'kVa',20,6);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Bayındır Tarım ',N'Tarımsal Sulama',N'Çivril',2024,100,N'kVa',800,7);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Bilal Çakmak',N'Tavuk Çiftliği',N'Tatar',2024,160,N'kVa',20,8);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Dg Hayvancılık',N'Tavuk Çiftliği',N'Uşak',2024,400,N'kVa',20,9);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Dg Hayvancılık',N'Tavuk Çiftliği',N'Uşak',2024,NULL,NULL,NULL,10);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Hs İnşaat Petrol',N'Benzin İstasyonu',N'Çivril',2024,250,N'kVa',20,11);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Latife Ünal',N'Tavuk Çiftliği',N'Çivril',2024,160,N'kVa',20,12);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Mcdog ',N'Tavuk Çiftliği',N'Çivril',2024,400,N'kVa',250,13);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Mcdog ',N'Tavuk Çiftliği',N'Çivril',2024,250,N'kVa',50,14);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Semercitürk Hayvancılık',N'Tavuk Çiftliği',N'Tatar',2024,400,N'kVa',20,15);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Yıldırhan İnşaat',N'Mobilizasyon',N'Bekilli',2024,250,N'kVa',100,16);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Çalık Holding',N'Ges Bağlantı Hattı',N'Tavas',2024,1250,N'kVa',3500,17);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'İlcan Gürel',N'Dokuma Fabrikası',N'Karahallı',2024,250,N'kVa',20,18);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Şahanlar Mühendislik',N'Tavuk Çiftliği',N'Çivril',2024,250,N'kVa',50,19);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Akbalık İnşaat',N'Tavuk Çiftliği',N'Çivril',2023,400,N'kVa',700,20);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Akbalık İnşaat',N'Tavuk Çiftliği',N'Çivril',2023,NULL,NULL,NULL,21);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Aktur Araç Muayene',N'Ges Bağlantı Hattı',N'Tavas',2023,2500,N'kVa',2000,22);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'As Umut Petrol Ltd Şti',N'Tarımsal Sulama',N'Çivril',2023,100,N'kVa',20,23);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'As Umut Petrol Ltd Şti',N'Tarımsal Sulama',N'Çivril',2023,250,N'kVa',20,24);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Bilgin Besicilik',N'Tavuk Çiftliği',N'Çivril',2023,400,N'kVa',20,25);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Bülent Aymergen',N'Tarımsal Sulama',N'Çivril',2023,100,N'kVa',20,26);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Damla Besicilik',N'Tavuk Çiftliği',N'Çivril',2023,100,N'kVa',400,27);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Denizli Ticaret Borsası',N'Çivril Lisanslı Depoculuk',N'Çivril',2023,1000,N'kVa',20,28);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Doğuş Hayvancılık',N'Tavuk Çiftliği',N'Tatar',2023,100,N'kVa',800,29);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Erkan Çakal',N'Tavuk Çiftliği',N'Sivaslı',2023,400,N'kVa',70,30);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Eryılmaz Dokuma',N'Dokuma Fabrikası',N'Karahallı',2023,400,N'kVa',20,31);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Hasan Döğer',N'Tavuk Çiftliği',N'Baklan',2023,400,N'kVa',20,32);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Hasan Önder',N'Soğuk Hava Deposu',N'Çivril',2023,400,N'kVa',20,33);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Hopa Çatı',N'Tavuk Çiftliği',N'Çivril',2023,NULL,NULL,NULL,34);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Hopa Çatı Ltd Şti',N'Tavuk Çiftliği',N'Çivril',2023,100,N'kVa',1700,35);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Mcdog',N'Mama Fabrikası',N'Çivril',2023,NULL,NULL,NULL,36);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Mck Mühendislik',N'Tavuk Çiftliği',N'Çivril',2023,400,N'kVa',800,37);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Murat Gökçen',N'Tavuk Çiftliği',N'Baklan',2023,400,N'kVa',20,38);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Pamukkale Soğuk Hava',N'Tavuk Çiftliği',N'Çivril',2023,400,N'kVa',100,39);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'İlcan Gürel',N'Dokuma Fabrikası',N'Karahallı',2023,NULL,NULL,NULL,40);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Şahan Cam',N'Cam Fabrikası',N'Uşak',2023,1600,N'kVa',500,41);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Şahan Cam',N'Cam Fabrikası',N'Uşak',2023,NULL,NULL,NULL,42);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Şemsettin Kıvrak',N'Tavuk Çiftliği',N'Çivril',2023,NULL,NULL,NULL,43);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Altun İnşaat',N'Güney Toki Elektrik Altyapı',N'Güney',2022,NULL,NULL,NULL,44);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Boso Madencilik',N'Mermer Fabrikası',N'Çivril',2022,NULL,NULL,NULL,45);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Dmr İnşaat',N'Mobilizasyon',N'Çivril',2022,50,N'kVa',20,46);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Er-ra Mermer',N'Mermer Fabrikası',N'Çivril',2022,400,N'kVa',20,47);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Eren Soğukhava',N'Soğuk Hava Deposu',N'Çivril',2022,630,N'kVa',600,48);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Esd Mimarlık',N'İnceler Toki Elektrik Altyapı',N'Bozkurt',2022,1000,N'kVa',200,49);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Esd Mimarlık',N'İnceler Toki Elektrik Altyapı',N'Bozkurt',2022,NULL,NULL,NULL,50);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Işık Pen',N'Pimapen Üretimi',N'Çivril',2022,400,N'kVa',450,51);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Mustafa Altın',N'Tavuk Çiftliği',N'Sandıklı',2022,NULL,NULL,NULL,52);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Oktay Hayvancılık',N'Tavuk Çiftliği',N'Çivril',2022,100,N'kVa',20,53);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Serdal Özelden',N'Tarımsal Sulama',N'Çivril',2022,100,N'kVa',400,54);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Tacettin Çorbacıoğlu',N'Besihane',N'Çivril',2022,100,N'kVa',300,55);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Uğur Türk',N'Depo',N'Çivril',2022,160,N'kVa',350,56);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Uşak İl Özel İdaresi',N'Tatar İçme Suyu Hattı',N'Tatar',2022,250,N'kVa',1700,57);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Volkan Ergun',N'Sıvı Gübre Üretimi',N'Çivril',2022,160,N'kVa',20,58);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Çetinkaya Yapı',N'Bekilli Mesirelik Alan Elektrik Altyapı',N'Bekilli',2022,NULL,NULL,NULL,59);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Altun İnşaat',N'Mobilizasyon',N'Güney',2021,160,N'kVa',750,60);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Altun İnşaat',N'Güney Toki Elektrik Altyapı',N'Güney',2021,630,N'kVa',50,61);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Avcı Kardeşler',N'Tavuk Çiftliği',N'Çivril',2021,NULL,NULL,NULL,62);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Bilgin Besicilik',N'Tavuk Çiftliği',N'Çivril',2021,160,N'kVa',300,63);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Bilgin Besicilik',N'Tavuk Çiftliği',N'Çivril',2021,NULL,NULL,NULL,64);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Boso Madencilik',N'Mermer Fabrikası',N'Çivril',2021,800,N'kVa',200,65);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Botaş',N'Baklan Pig İstasyonu',N'Baklan',2021,10,N'kVa',2500,66);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Duraksan Madencilik',N'Kömür Ocağı',N'Kale',2021,800,N'kVa',1000,67);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Ercan Manav',N'Soğuk Hava Deposu',N'Çivril',2021,NULL,NULL,NULL,68);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Eşe Özcan',N'Tavuk Çiftliği',N'Çivril',2021,600,N'kVa',7,69);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Halil Ertuğrul',N'Tavuk Çiftliği',N'Çivril',2021,160,N'kVa',600,70);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Muhittin Şen',N'Tavuk Çiftliği',N'Çivril',2021,160,N'kVa',500,71);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Muhittin Şen',N'Tavuk Çiftliği',N'Çivril',2021,NULL,NULL,NULL,72);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Murat Özbay',N'Tavuk Çiftliği',N'Sivaslı',2021,100,N'kVa',20,73);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Ramazan Çakır',N'Dokuma Fabrikası',N'Karahallı',2021,250,N'kVa',20,74);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Ramazan Çakır',N'Dokuma Fabrikası',N'Karahallı',2021,NULL,NULL,NULL,75);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Sağlık Bakanlığı',N'Çivril Devlet Hastanesi Diş Polikliniği',N'Çivril',2021,NULL,NULL,NULL,76);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Shemsa Naturel',N'Aromatik Bitki İşleme',N'Çivril',2021,160,N'kVa',600,77);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Süleyman Saman',N'Tavuk Çiftliği',N'Çivril',2021,160,N'kVa',400,78);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Taner Danacı',N'Besihane',N'Çivril',2021,100,N'kVa',20,79);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Yılkanur İnşaat',N'Mobilizasyon',N'Çivril',2021,250,N'kVa',1100,80);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Yılkanur İnşaat',N'Çivril Toki Mobilizasyon',N'Çivril',2021,NULL,NULL,NULL,81);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'As Umut Petrol Ltd Şti',N'Tarımsal Sulama',N'Çivril',2020,160,N'kVa',1650,82);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Halil Ertuğrul',N'Tavuk Çiftliği',N'Çivril',2020,NULL,NULL,NULL,83);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Kocaman İnşaat',N'Bekilli Toki Elektrik Altyapı',N'Bekilli',2020,630,N'kVa',600,84);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Kocaman İnşaat',N'Bekilli Toki Elektrik Altyapı',N'Bekilli',2020,NULL,NULL,NULL,85);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Mdo Ges',N'Ges Bağlantı Hattı',N'Çivril',2020,400,N'kVa',1200,86);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Ramazan Akyürek',N'Kereste İmalatı',N'Çivril',2020,100,N'kVa',100,87);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Duraksan Madencilik',N'Kömür Ocağı',N'Kale',2019,400,N'kVa',100,88);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Ercan Manav',N'Soğuk Hava Deposu',N'Çivril',2019,400,N'kVa',70,89);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Memiş Memiş',N'Besihane',N'Çivril',2019,50,N'kVa',20,90);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Murat Cemil Hayta',N'Besihane',N'Çal',2019,50,N'kVa',800,91);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Sarıosmanoğlu İnşaat',N'Mobilizasyon',N'Çivril',2019,50,N'kVa',20,92);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Alparslan Balaban',N'Tarımsal Sulama',N'Çivril',2018,100,N'kVa',20,93);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Duraksan Madencilik',N'Kömür Ocağı',N'Kale',2018,2000,N'kVa',1500,94);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Selami Akar',N'Besihane',N'Çivril',2018,50,N'kVa',50,95);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Şevket Akıncı',N'Tavuk Çiftliği',N'Çivril',2018,50,N'kVa',20,96);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'Yusuf Garip',N'Sera',N'Çivril',2017,50,N'kVa',700,97);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,29610,N'kVa',33077,98);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,99);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,100);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,101);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,102);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,103);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,104);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,105);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,106);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,107);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,108);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,109);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,110);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,111);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,112);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,113);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,114);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,115);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,116);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,117);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,118);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,119);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,120);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,121);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,122);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,123);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,124);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,125);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,126);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,127);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,128);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,129);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,130);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,131);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,132);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,133);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,134);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,135);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,136);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,137);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,138);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,139);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,140);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,141);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,142);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,143);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,144);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,145);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,146);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,147);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,148);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,149);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,150);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,151);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,152);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,153);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,154);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,155);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,156);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,157);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,158);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,159);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,160);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,161);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,162);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,163);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,164);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,165);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,166);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,167);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,168);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,169);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,170);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,171);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,172);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,173);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,174);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,175);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,176);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,177);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,178);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,179);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,180);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,181);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,182);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,183);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,184);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,185);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,186);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,187);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,188);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,189);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,190);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,191);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,192);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,193);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,194);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,195);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,196);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,197);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,198);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,199);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,200);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,201);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,202);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,203);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,204);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,205);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,206);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,207);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,208);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,209);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,210);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,211);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,212);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,213);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,214);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,215);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,216);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,217);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,218);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,219);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,220);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,221);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,222);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,223);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,224);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,225);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,226);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,227);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,228);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,229);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,230);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,231);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,232);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,233);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,234);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,235);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik',N'',N'',N'',NULL,NULL,NULL,NULL,236);

-- Elektrik: öne çıkan 4 proje (fotoğraflı, is_featured=1)
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,enh_meters,unit_count,photo_filename,is_featured,sort_order) VALUES ('elektrik',N'Aktifbank GES E.N.H.',N'ENH',N'Denizli',NULL,NULL,3500,134,N'enh-aktifbank.jpg',1,0);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,enh_meters,unit_count,photo_filename,is_featured,sort_order) VALUES ('elektrik',N'Baklan Pik İstasyonu',N'ENH',N'Denizli',NULL,NULL,2500,118,N'enh-baklan-pik.jpg',1,1);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,enh_meters,unit_count,photo_filename,is_featured,sort_order) VALUES ('elektrik',N'Tatar İçme Suyu',N'ENH',N'Uşak',NULL,NULL,1800,158,N'enh-tatar-icme-suyu.jpg',1,2);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,enh_meters,unit_count,photo_filename,is_featured,sort_order) VALUES ('elektrik',N'Şahan Cam',N'Trafo',N'Uşak',1600,N'kVa',NULL,440,N'enh-sahan-cam.jpg',1,3);-- Asansör
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'Ercan Manav',N'Apartman',N'Çivril',2024,1,0);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'H&s İnşaat',N'Apartman',N'Çivril',2024,1,1);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'Mehmet Ali',N'Apartman',N'Çivril',2024,1,2);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'Yıldırhan İnşaat',N'Toki',N'Bekilli',2024,17,3);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'Hüseyin Şahan',N'Apartman',N'Çivril',2023,1,4);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'Nazmi Oskay',N'Apartman',N'Çivril',2023,1,5);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'İsa Erdoğan',N'Apartman',N'Çivril',2023,1,6);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'Güntürk İnşaat',N'İşhanı',N'Çivril',2021,1,7);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'Kandemirler Mobilya',N'Yük Asansörü',N'Çivril',2021,1,8);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'Map Yapı',N'Apartman',N'Çivril',2021,1,9);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'Zeki Bey',N'Engelli Asansörü',N'Çivril',2021,1,10);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'Özkan Avcı',N'Apartman',N'Çivril',2021,1,11);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'Tab Mimarlık',N'Apartman',N'Çivril',2020,1,12);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor',N'Ümit Çelik',N'Apartman',N'Çivril',2020,1,13);-- Enerji (GES): fotoğraflı 13 öne çıkan + Excel 16 kayıt
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Turkuaz Otomotiv',N'Çatı Tipi',N'Denizli',500,N'kW',N'ges-turkuaz-otomotiv.jpg',1,0);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Aktur GES',N'Arazi Tipi',N'Tavas/Denizli',2200,N'kW',N'ges-aktur-ges.jpg',1,1);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Ecogreen',N'Arazi Tipi',N'Tavas/Denizli',8000,N'kW',N'ges-ecogreen-8.jpg',1,2);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Ecogreen',N'Arazi Tipi',N'Tavas/Denizli',3000,N'kW',N'ges-ecogreen-3.jpg',1,3);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Çalık Enerji',N'Arazi Tipi',N'Tavas/Denizli',1300,N'kW',N'ges-calik-enerji.jpg',1,4);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Altıntop',N'Arazi Tipi',N'Denizli',1300,N'kW',N'ges-altintop.jpg',1,5);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Sivaslı Kaymakamlığı (Filtorq-Filtor)',N'Arazi Tipi',N'Uşak',475,N'kW',N'ges-sivasli-kaymakamligi.jpg',1,6);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Turkuaz Tekstil',N'Çatı Tipi',N'Denizli',1900,N'kW',N'ges-turkuaz-tekstil.jpg',1,7);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Aysan Raf',N'Çatı Tipi',N'Denizli',1200,N'kW',N'ges-aysan-raf.jpg',1,8);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Öz-Sa Mensucat',N'Çatı Tipi',N'Denizli',450,N'kW',N'ges-6z-sa-mensucat.jpg',1,9);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Ercan Manav',N'Çatı Tipi',N'Denizli',410,N'kW',N'ges-ercan-manav.jpg',1,10);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Güney Hayvancılık 2',N'Çatı Tipi',N'Uşak',400,N'kW',N'ges-guney-hayvancilik-2.jpg',1,11);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji',N'Emsal Kuruyemiş',N'Çatı Tipi',N'Osmaniye',440,N'kW',N'ges-emsal-kuruyemis.jpg',1,12);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'Bilgin Besicilikges',N'Çatı Tipi',N'Çivril',2022,130,N'kW',13);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'İpel Tül Ges-1',N'Çatı Tipi',N'Çorlu',2023,3900,N'kW',14);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'Tanrıkulu Tarım Ges',N'Çatı Tipi',N'Çivril',2023,310,N'kW',15);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'Dasila Soft',N'Çatı Tipi',N'Burdur',2023,125,N'kW',16);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'Bilgin Tarım',N'Çatı Tipi',N'Çivril',2023,130,N'kW',17);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'Akay Soğuk Hava',N'Çatı Tipi',N'Çivril',2023,108,N'kW',18);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'Boso Madencilik',N'Çatı Tipi',N'Çivril',2023,500,N'kW',19);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'İhlas Besicilik',N'Çatı Tipi',N'Çivril',2023,72,N'kW',20);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'Numanoğlu Ticaret',N'Çatı Tipi',N'Çivril',2023,120,N'kW',21);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'Şevket Akıncı',N'Çatı Tipi',N'Çivril',2023,180,N'kW',22);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'Bulutlar Soğuk Hava',N'Çatı Tipi',N'Çivril',2023,720,N'kW',23);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'İpek Tül Ges-2',N'Çatı Tipi',N'Çorlu',2024,2100,N'kW',24);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'Önderler Soğuk Hava',N'Çatı Tipi',N'Çivril',2024,325,N'kW',25);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'İhlas Soğuk Hava',N'Çatı Tipi',N'Çivril',2024,325,N'kW',26);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'Kanyon Koleji',N'Çatı Tipi',N'Uşak',2024,200,N'kW',27);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji',N'Demirtaş Kömür',N'Arazi Tipi',N'Çivril',2025,1072,N'kW',28);-- Yazılım: bilinen 4 ürün
INSERT INTO site_references (category,name,ref_type,location,ref_year,is_featured,sort_order) VALUES ('yazilim',N'Perde Otomasyon Programı',N'İşletme Yazılımı',NULL,NULL,1,0);
INSERT INTO site_references (category,name,ref_type,location,ref_year,is_featured,sort_order) VALUES ('yazilim',N'Fx (Muhasebe) Programı',N'İşletme Yazılımı',NULL,NULL,1,1);
INSERT INTO site_references (category,name,ref_type,location,ref_year,is_featured,sort_order) VALUES ('yazilim',N'POS Takip Programı',N'İşletme Yazılımı',NULL,NULL,1,2);
INSERT INTO site_references (category,name,ref_type,location,ref_year,is_featured,sort_order) VALUES ('yazilim',N'Kasa Defterim Programı',N'İşletme Yazılımı',NULL,NULL,1,3);-- Hayvancılık ve Tarım
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,photo_filename,is_featured,sort_order) VALUES ('hayvancilik',N'Etlik Piliç Tesisi',N'Etlik Piliç',N'Karalar, Çivril / Denizli',2024,30000,N'gallery-hayvancilik-1.jpg',1,0);
INSERT INTO site_references (category,name,ref_type,location,ref_year,is_featured,sort_order) VALUES ('tarim',N'Yamanlar Arazisi',N'Planlanan',N'Yamanlar, Çivril / Denizli',2026,1,0);-- Ekip
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Yakup Ahmet Şahan',N'Elektrik-Elektronik Mühendisi · Şirket Sahibi',N'Mühendislik Ekibi',0);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Gözde Şahan',N'Elektrik-Elektronik Mühendisi · Şirket Sahibi',N'Mühendislik Ekibi',1);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Rüveyda Akkaya',N'Elektrik-Elektronik Mühendisi',N'Mühendislik Ekibi',2);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Ekrem Gümüş',N'Elektrik-Elektronik Mühendisi',N'Mühendislik Ekibi',3);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Şuayip Erişsel',N'Koordinatör',N'Koordinasyon & Ofis',4);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Hatice Büyükkal',N'Müşteri İlişkileri',N'Koordinasyon & Ofis',5);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Dudu Akkoyun',N'Muhasebe Birimi',N'Koordinasyon & Ofis',6);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Hüseyin Türkyılmaz',N'Elektrik Teknisyeni',N'Teknik Ekip',7);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Yusuf Kurtuva',N'Elektrik Teknisyeni',N'Teknik Ekip',8);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Ali Küçük',N'Elektrik Teknisyeni',N'Teknik Ekip',9);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Ardahan Kazan',N'Elektrik Teknikeri',N'Teknik Ekip',10);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Hasan Küçük',N'Elektrik Teknikeri',N'Teknik Ekip',11);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES (N'Ziya Deniz',N'Elektrik Teknikeri',N'Teknik Ekip',12);