-- ============================================================
-- Şahanlar Mühendislik — Tüm Başlangıç Verileri (seed.sql)
-- Sırayla çalıştırın: 1) schema.sql   2) seed.sql
-- ============================================================
SET NAMES utf8;

-- ============================================================
-- Şahanlar Mühendislik — Başlangıç Verisi (site_references)
-- schema.sql'den SONRA çalıştırın.
-- ============================================================
SET NAMES utf8;

-- Elektrik: 237 kayıt
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Ahmet Emrem','Tarımsal Sulama','Çivril',2025,100,'kVa',50,0);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Aou Gıda','Tavuk Çiftliği','Çivril',2025,400,'kVa',400,1);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Demirtaş Kömür','Ges Bağlantı Hattı','Çivril',2025,1000,'kVa',500,2);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Harun Sarıkaya','Tavuk Çiftliği','Çivril',2025,400,'kVa',900,3);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Ümit Çelik','Güç Yükseltimi','Çivril',2025,400,'kVa',20,4);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Altıntop Kuruyemiş','Ges Bağlantı Hattı','Tavas',2024,1000,'kVa',70,5);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Antav Hayvancılık','Tavuk Çiftliği','Çivril',2024,400,'kVa',20,6);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Bayındır Tarım ','Tarımsal Sulama','Çivril',2024,100,'kVa',800,7);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Bilal Çakmak','Tavuk Çiftliği','Tatar',2024,160,'kVa',20,8);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Dg Hayvancılık','Tavuk Çiftliği','Uşak',2024,400,'kVa',20,9);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Dg Hayvancılık','Tavuk Çiftliği','Uşak',2024,NULL,NULL,NULL,10);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Hs İnşaat Petrol','Benzin İstasyonu','Çivril',2024,250,'kVa',20,11);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Latife Ünal','Tavuk Çiftliği','Çivril',2024,160,'kVa',20,12);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Mcdog ','Tavuk Çiftliği','Çivril',2024,400,'kVa',250,13);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Mcdog ','Tavuk Çiftliği','Çivril',2024,250,'kVa',50,14);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Semercitürk Hayvancılık','Tavuk Çiftliği','Tatar',2024,400,'kVa',20,15);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Yıldırhan İnşaat','Mobilizasyon','Bekilli',2024,250,'kVa',100,16);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Çalık Holding','Ges Bağlantı Hattı','Tavas',2024,1250,'kVa',3500,17);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','İlcan Gürel','Dokuma Fabrikası','Karahallı',2024,250,'kVa',20,18);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Şahanlar Mühendislik','Tavuk Çiftliği','Çivril',2024,250,'kVa',50,19);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Akbalık İnşaat','Tavuk Çiftliği','Çivril',2023,400,'kVa',700,20);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Akbalık İnşaat','Tavuk Çiftliği','Çivril',2023,NULL,NULL,NULL,21);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Aktur Araç Muayene','Ges Bağlantı Hattı','Tavas',2023,2500,'kVa',2000,22);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','As Umut Petrol Ltd Şti','Tarımsal Sulama','Çivril',2023,100,'kVa',20,23);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','As Umut Petrol Ltd Şti','Tarımsal Sulama','Çivril',2023,250,'kVa',20,24);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Bilgin Besicilik','Tavuk Çiftliği','Çivril',2023,400,'kVa',20,25);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Bülent Aymergen','Tarımsal Sulama','Çivril',2023,100,'kVa',20,26);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Damla Besicilik','Tavuk Çiftliği','Çivril',2023,100,'kVa',400,27);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Denizli Ticaret Borsası','Çivril Lisanslı Depoculuk','Çivril',2023,1000,'kVa',20,28);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Doğuş Hayvancılık','Tavuk Çiftliği','Tatar',2023,100,'kVa',800,29);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Erkan Çakal','Tavuk Çiftliği','Sivaslı',2023,400,'kVa',70,30);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Eryılmaz Dokuma','Dokuma Fabrikası','Karahallı',2023,400,'kVa',20,31);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Hasan Döğer','Tavuk Çiftliği','Baklan',2023,400,'kVa',20,32);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Hasan Önder','Soğuk Hava Deposu','Çivril',2023,400,'kVa',20,33);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Hopa Çatı','Tavuk Çiftliği','Çivril',2023,NULL,NULL,NULL,34);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Hopa Çatı Ltd Şti','Tavuk Çiftliği','Çivril',2023,100,'kVa',1700,35);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Mcdog','Mama Fabrikası','Çivril',2023,NULL,NULL,NULL,36);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Mck Mühendislik','Tavuk Çiftliği','Çivril',2023,400,'kVa',800,37);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Murat Gökçen','Tavuk Çiftliği','Baklan',2023,400,'kVa',20,38);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Pamukkale Soğuk Hava','Tavuk Çiftliği','Çivril',2023,400,'kVa',100,39);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','İlcan Gürel','Dokuma Fabrikası','Karahallı',2023,NULL,NULL,NULL,40);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Şahan Cam','Cam Fabrikası','Uşak',2023,1600,'kVa',500,41);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Şahan Cam','Cam Fabrikası','Uşak',2023,NULL,NULL,NULL,42);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Şemsettin Kıvrak','Tavuk Çiftliği','Çivril',2023,NULL,NULL,NULL,43);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Altun İnşaat','Güney Toki Elektrik Altyapı','Güney',2022,NULL,NULL,NULL,44);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Boso Madencilik','Mermer Fabrikası','Çivril',2022,NULL,NULL,NULL,45);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Dmr İnşaat','Mobilizasyon','Çivril',2022,50,'kVa',20,46);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Er-ra Mermer','Mermer Fabrikası','Çivril',2022,400,'kVa',20,47);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Eren Soğukhava','Soğuk Hava Deposu','Çivril',2022,630,'kVa',600,48);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Esd Mimarlık','İnceler Toki Elektrik Altyapı','Bozkurt',2022,1000,'kVa',200,49);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Esd Mimarlık','İnceler Toki Elektrik Altyapı','Bozkurt',2022,NULL,NULL,NULL,50);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Işık Pen','Pimapen Üretimi','Çivril',2022,400,'kVa',450,51);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Mustafa Altın','Tavuk Çiftliği','Sandıklı',2022,NULL,NULL,NULL,52);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Oktay Hayvancılık','Tavuk Çiftliği','Çivril',2022,100,'kVa',20,53);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Serdal Özelden','Tarımsal Sulama','Çivril',2022,100,'kVa',400,54);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Tacettin Çorbacıoğlu','Besihane','Çivril',2022,100,'kVa',300,55);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Uğur Türk','Depo','Çivril',2022,160,'kVa',350,56);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Uşak İl Özel İdaresi','Tatar İçme Suyu Hattı','Tatar',2022,250,'kVa',1700,57);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Volkan Ergun','Sıvı Gübre Üretimi','Çivril',2022,160,'kVa',20,58);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Çetinkaya Yapı','Bekilli Mesirelik Alan Elektrik Altyapı','Bekilli',2022,NULL,NULL,NULL,59);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Altun İnşaat','Mobilizasyon','Güney',2021,160,'kVa',750,60);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Altun İnşaat','Güney Toki Elektrik Altyapı','Güney',2021,630,'kVa',50,61);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Avcı Kardeşler','Tavuk Çiftliği','Çivril',2021,NULL,NULL,NULL,62);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Bilgin Besicilik','Tavuk Çiftliği','Çivril',2021,160,'kVa',300,63);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Bilgin Besicilik','Tavuk Çiftliği','Çivril',2021,NULL,NULL,NULL,64);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Boso Madencilik','Mermer Fabrikası','Çivril',2021,800,'kVa',200,65);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Botaş','Baklan Pig İstasyonu','Baklan',2021,10,'kVa',2500,66);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Duraksan Madencilik','Kömür Ocağı','Kale',2021,800,'kVa',1000,67);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Ercan Manav','Soğuk Hava Deposu','Çivril',2021,NULL,NULL,NULL,68);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Eşe Özcan','Tavuk Çiftliği','Çivril',2021,600,'kVa',7,69);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Halil Ertuğrul','Tavuk Çiftliği','Çivril',2021,160,'kVa',600,70);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Muhittin Şen','Tavuk Çiftliği','Çivril',2021,160,'kVa',500,71);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Muhittin Şen','Tavuk Çiftliği','Çivril',2021,NULL,NULL,NULL,72);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Murat Özbay','Tavuk Çiftliği','Sivaslı',2021,100,'kVa',20,73);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Ramazan Çakır','Dokuma Fabrikası','Karahallı',2021,250,'kVa',20,74);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Ramazan Çakır','Dokuma Fabrikası','Karahallı',2021,NULL,NULL,NULL,75);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Sağlık Bakanlığı','Çivril Devlet Hastanesi Diş Polikliniği','Çivril',2021,NULL,NULL,NULL,76);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Shemsa Naturel','Aromatik Bitki İşleme','Çivril',2021,160,'kVa',600,77);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Süleyman Saman','Tavuk Çiftliği','Çivril',2021,160,'kVa',400,78);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Taner Danacı','Besihane','Çivril',2021,100,'kVa',20,79);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Yılkanur İnşaat','Mobilizasyon','Çivril',2021,250,'kVa',1100,80);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Yılkanur İnşaat','Çivril Toki Mobilizasyon','Çivril',2021,NULL,NULL,NULL,81);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','As Umut Petrol Ltd Şti','Tarımsal Sulama','Çivril',2020,160,'kVa',1650,82);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Halil Ertuğrul','Tavuk Çiftliği','Çivril',2020,NULL,NULL,NULL,83);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Kocaman İnşaat','Bekilli Toki Elektrik Altyapı','Bekilli',2020,630,'kVa',600,84);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Kocaman İnşaat','Bekilli Toki Elektrik Altyapı','Bekilli',2020,NULL,NULL,NULL,85);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Mdo Ges','Ges Bağlantı Hattı','Çivril',2020,400,'kVa',1200,86);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Ramazan Akyürek','Kereste İmalatı','Çivril',2020,100,'kVa',100,87);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Duraksan Madencilik','Kömür Ocağı','Kale',2019,400,'kVa',100,88);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Ercan Manav','Soğuk Hava Deposu','Çivril',2019,400,'kVa',70,89);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Memiş Memiş','Besihane','Çivril',2019,50,'kVa',20,90);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Murat Cemil Hayta','Besihane','Çal',2019,50,'kVa',800,91);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Sarıosmanoğlu İnşaat','Mobilizasyon','Çivril',2019,50,'kVa',20,92);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Alparslan Balaban','Tarımsal Sulama','Çivril',2018,100,'kVa',20,93);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Duraksan Madencilik','Kömür Ocağı','Kale',2018,2000,'kVa',1500,94);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Selami Akar','Besihane','Çivril',2018,50,'kVa',50,95);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Şevket Akıncı','Tavuk Çiftliği','Çivril',2018,50,'kVa',20,96);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','Yusuf Garip','Sera','Çivril',2017,50,'kVa',700,97);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,29610,'kVa',33077,98);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,99);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,100);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,101);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,102);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,103);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,104);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,105);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,106);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,107);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,108);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,109);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,110);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,111);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,112);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,113);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,114);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,115);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,116);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,117);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,118);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,119);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,120);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,121);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,122);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,123);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,124);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,125);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,126);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,127);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,128);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,129);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,130);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,131);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,132);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,133);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,134);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,135);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,136);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,137);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,138);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,139);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,140);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,141);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,142);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,143);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,144);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,145);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,146);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,147);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,148);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,149);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,150);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,151);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,152);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,153);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,154);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,155);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,156);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,157);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,158);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,159);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,160);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,161);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,162);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,163);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,164);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,165);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,166);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,167);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,168);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,169);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,170);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,171);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,172);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,173);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,174);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,175);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,176);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,177);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,178);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,179);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,180);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,181);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,182);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,183);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,184);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,185);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,186);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,187);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,188);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,189);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,190);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,191);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,192);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,193);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,194);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,195);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,196);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,197);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,198);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,199);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,200);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,201);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,202);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,203);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,204);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,205);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,206);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,207);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,208);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,209);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,210);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,211);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,212);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,213);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,214);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,215);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,216);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,217);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,218);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,219);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,220);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,221);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,222);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,223);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,224);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,225);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,226);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,227);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,228);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,229);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,230);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,231);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,232);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,233);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,234);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,235);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,enh_meters,sort_order) VALUES ('elektrik','','','',NULL,NULL,NULL,NULL,236);

-- Elektrik: öne çıkan 4 proje (fotoğraflı, is_featured=1)
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,enh_meters,unit_count,photo_filename,is_featured,sort_order) VALUES ('elektrik','Aktifbank GES E.N.H.','ENH','Denizli',NULL,NULL,3500,134,'enh-aktifbank.jpg',1,0);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,enh_meters,unit_count,photo_filename,is_featured,sort_order) VALUES ('elektrik','Baklan Pik İstasyonu','ENH','Denizli',NULL,NULL,2500,118,'enh-baklan-pik.jpg',1,1);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,enh_meters,unit_count,photo_filename,is_featured,sort_order) VALUES ('elektrik','Tatar İçme Suyu','ENH','Uşak',NULL,NULL,1800,158,'enh-tatar-icme-suyu.jpg',1,2);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,enh_meters,unit_count,photo_filename,is_featured,sort_order) VALUES ('elektrik','Şahan Cam','Trafo','Uşak',1600,'kVa',NULL,440,'enh-sahan-cam.jpg',1,3);-- Asansör
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','Ercan Manav','Apartman','Çivril',2024,1,0);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','H&s İnşaat','Apartman','Çivril',2024,1,1);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','Mehmet Ali','Apartman','Çivril',2024,1,2);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','Yıldırhan İnşaat','Toki','Bekilli',2024,17,3);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','Hüseyin Şahan','Apartman','Çivril',2023,1,4);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','Nazmi Oskay','Apartman','Çivril',2023,1,5);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','İsa Erdoğan','Apartman','Çivril',2023,1,6);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','Güntürk İnşaat','İşhanı','Çivril',2021,1,7);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','Kandemirler Mobilya','Yük Asansörü','Çivril',2021,1,8);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','Map Yapı','Apartman','Çivril',2021,1,9);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','Zeki Bey','Engelli Asansörü','Çivril',2021,1,10);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','Özkan Avcı','Apartman','Çivril',2021,1,11);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','Tab Mimarlık','Apartman','Çivril',2020,1,12);
INSERT INTO site_references (category,name,ref_type,location,ref_year,unit_count,sort_order) VALUES ('asansor','Ümit Çelik','Apartman','Çivril',2020,1,13);-- Enerji (GES): fotoğraflı 13 öne çıkan + Excel 16 kayıt
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Turkuaz Otomotiv','Çatı Tipi','Denizli',500,'kW','ges-turkuaz-otomotiv.jpg',1,0);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Aktur GES','Arazi Tipi','Tavas/Denizli',2200,'kW','ges-aktur-ges.jpg',1,1);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Ecogreen','Arazi Tipi','Tavas/Denizli',8000,'kW','ges-ecogreen-8.jpg',1,2);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Ecogreen','Arazi Tipi','Tavas/Denizli',3000,'kW','ges-ecogreen-3.jpg',1,3);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Çalık Enerji','Arazi Tipi','Tavas/Denizli',1300,'kW','ges-calik-enerji.jpg',1,4);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Altıntop','Arazi Tipi','Denizli',1300,'kW','ges-altintop.jpg',1,5);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Sivaslı Kaymakamlığı (Filtorq-Filtor)','Arazi Tipi','Uşak',475,'kW','ges-sivasli-kaymakamligi.jpg',1,6);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Turkuaz Tekstil','Çatı Tipi','Denizli',1900,'kW','ges-turkuaz-tekstil.jpg',1,7);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Aysan Raf','Çatı Tipi','Denizli',1200,'kW','ges-aysan-raf.jpg',1,8);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Öz-Sa Mensucat','Çatı Tipi','Denizli',450,'kW','ges-6z-sa-mensucat.jpg',1,9);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Ercan Manav','Çatı Tipi','Denizli',410,'kW','ges-ercan-manav.jpg',1,10);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Güney Hayvancılık 2','Çatı Tipi','Uşak',400,'kW','ges-guney-hayvancilik-2.jpg',1,11);
INSERT INTO site_references (category,name,ref_type,location,power_value,power_unit,photo_filename,is_featured,sort_order) VALUES ('enerji','Emsal Kuruyemiş','Çatı Tipi','Osmaniye',440,'kW','ges-emsal-kuruyemis.jpg',1,12);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','Bilgin Besicilikges','Çatı Tipi','Çivril',2022,130,'kW',13);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','İpel Tül Ges-1','Çatı Tipi','Çorlu',2023,3900,'kW',14);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','Tanrıkulu Tarım Ges','Çatı Tipi','Çivril',2023,310,'kW',15);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','Dasila Soft','Çatı Tipi','Burdur',2023,125,'kW',16);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','Bilgin Tarım','Çatı Tipi','Çivril',2023,130,'kW',17);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','Akay Soğuk Hava','Çatı Tipi','Çivril',2023,108,'kW',18);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','Boso Madencilik','Çatı Tipi','Çivril',2023,500,'kW',19);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','İhlas Besicilik','Çatı Tipi','Çivril',2023,72,'kW',20);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','Numanoğlu Ticaret','Çatı Tipi','Çivril',2023,120,'kW',21);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','Şevket Akıncı','Çatı Tipi','Çivril',2023,180,'kW',22);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','Bulutlar Soğuk Hava','Çatı Tipi','Çivril',2023,720,'kW',23);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','İpek Tül Ges-2','Çatı Tipi','Çorlu',2024,2100,'kW',24);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','Önderler Soğuk Hava','Çatı Tipi','Çivril',2024,325,'kW',25);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','İhlas Soğuk Hava','Çatı Tipi','Çivril',2024,325,'kW',26);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','Kanyon Koleji','Çatı Tipi','Uşak',2024,200,'kW',27);
INSERT INTO site_references (category,name,ref_type,location,ref_year,power_value,power_unit,sort_order) VALUES ('enerji','Demirtaş Kömür','Arazi Tipi','Çivril',2025,1072,'kW',28);-- Yazılım: bilinen 4 ürün
INSERT INTO site_references (category,name,ref_type,location,ref_year,is_featured,sort_order) VALUES ('yazilim','Perde Otomasyon Programı','İşletme Yazılımı',NULL,NULL,1,0);
INSERT INTO site_references (category,name,ref_type,location,ref_year,is_featured,sort_order) VALUES ('yazilim','Fx (Muhasebe) Programı','İşletme Yazılımı',NULL,NULL,1,1);
INSERT INTO site_references (category,name,ref_type,location,ref_year,is_featured,sort_order) VALUES ('yazilim','POS Takip Programı','İşletme Yazılımı',NULL,NULL,1,2);
INSERT INTO site_references (category,name,ref_type,location,ref_year,is_featured,sort_order) VALUES ('yazilim','Kasa Defterim Programı','İşletme Yazılımı',NULL,NULL,1,3);-- Ekip
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Yakup Ahmet Şahan','Elektrik-Elektronik Mühendisi · Şirket Sahibi','Mühendislik Ekibi',0);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Gözde Şahan','Elektrik-Elektronik Mühendisi · Şirket Sahibi','Mühendislik Ekibi',1);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Rüveyda Akkaya','Elektrik-Elektronik Mühendisi','Mühendislik Ekibi',2);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Ekrem Gümüş','Elektrik-Elektronik Mühendisi','Mühendislik Ekibi',3);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Şuayip Erişsel','Koordinatör','Koordinasyon & Ofis',4);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Hatice Büyükkal','Müşteri İlişkileri','Koordinasyon & Ofis',5);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Dudu Akkoyun','Muhasebe Birimi','Koordinasyon & Ofis',6);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Hüseyin Türkyılmaz','Elektrik Teknisyeni','Teknik Ekip',7);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Yusuf Kurtuva','Elektrik Teknisyeni','Teknik Ekip',8);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Ali Küçük','Elektrik Teknisyeni','Teknik Ekip',9);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Ardahan Kazan','Elektrik Teknikeri','Teknik Ekip',10);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Hasan Küçük','Elektrik Teknikeri','Teknik Ekip',11);
INSERT INTO team_members (full_name,role_title,team_group,sort_order) VALUES ('Ziya Deniz','Elektrik Teknikeri','Teknik Ekip',12);